### ISSUE TITLE
如何用 css 或 js 实现多行文本溢出省略效果

### ISSUE THREAD

**Issue by MrSeaWave** [MrSeaWave/interview#62]
单行文本溢出

```css
text-overflow: ellipsis; 
overflow: hidden;
white-space: nowrap
```

多行文本：

WebKit内核浏览器解决办法
首先，WebKit内核的浏览器实现起来比较简单，可以通过添加一个-webkit-line-clamp的私有属性来实现，-webkit-line-clamp是用来限制在一个块元素显示的文本的行数。 为了实现这个效果，它需要组合其他的WebKit属性：

    display: -webkit-box 将对象作为弹性伸缩盒子模型显示；
    -webkit-box-orient 设置或检索伸缩盒对象的子元素的排列方式；
    text-overflow: ellipsis 用省略号“…”隐藏超出范围的文本。

具体代码参考如下：

```css
display: -webkit-box;
-webkit-line-clamp: 2; 
-webkit-box-orient: vertical;
text-overflow: ellipsis;
overflow: hidden;
```

**Comment by MrSeaWave** [comment]
其他浏览器的解决方案
目前没有什么CSS的属性可以直接控制多行文本的省略显示，比较靠谱的办法应该就是利用相对定位在最后面加上一个省略号了，代码可以参考下面：

```css
p {
    position:relative;
    line-height:1.5em;
    /* 高度为需要显示的行数*行高，比如这里我们显示两行，则为3 */
    height:3em;
    overflow:hidden;
}
p:after {
    content:"...";
    position:absolute;
    bottom:0;
    right:0;
    padding: 0 5px;
    background-color: #fff;
}

```

效果如下： 
不过这样会有一点问题：

    1. 需要知道显示的行数并设置行高才行；
    2. IE6/7不支持after和content，需要添加一个标签来代替；
    3. 省略号的背景颜色跟文本背景颜色一样，并且可能会遮住部分文字，建议可以使用渐变的png背景图片代替。
